package P6Paste::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

my $dsn = $ENV{MYAPP_DSN} // 'dbi:SQLite:p6paste.db';
__PACKAGE__->config(
    schema_class => 'P6Paste::Schema',
    
    connect_info => {
        dsn => $dsn,
        user => '',
        password => '',
    }
);

=head1 NAME

P6Paste::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<P6Paste>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<P6Paste::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

Jason Felds

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
